name: Importmap updates
on:
  schedule:
    - cron: "0 9 * * 1"   # Mondays 09:00 UTC
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: thoughtbot/importmap-update@6d4f577f14051f89785746272460ce668affd8bf
        with:
          github-token: ${{ secrets.IMPORTMAP_UPDATE_GH_TOKEN }}
